language: python
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"

branches:
    only:
        - master
        - dev

virtualenv:
system_site_packages: true


# from https://conda.io/docs/travis.html
install:
    - sudo apt-get update 

    # install conda
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi

    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
      
    # Useful for debugging any issues with conda
    - conda info -a
    - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION

    # now install package specific dependencies
    - conda install -n test-environment -c conda-forge matplotlib
    - conda install -q -n test-environment -c conda-forge scipy python-cdo basemap cartopy netcdf4 pyshp cython shapely

    # now install package
    - source activate test-environment
    - python setup.py build_ext --inplace
    - python setup.py install



#before_install:


# basic python modules
#- sudo apt-get install python-numpy
  #- sudo apt-get install python-scipy
# todo clarify alternative installation for SCIPY to allow for most recent version ??
#- pip install pyparsing
#- pip install matplotlib
#- sudo apt-get install python-mpltoolkits.basemap python-mpltoolkits.basemap-data

# projection libraries
#- sudo apt-get install libgeos-dev libproj-dev

# testing environment
# - pip install coveralls pytest-cov

# I/O related things
# - sudo apt-get install libhdf5-openmpi-dev libnetcdf-dev libopenmpi-dev
# - sudo apt-get install libgdal1h
# - sudo apt-get install libgdal-dev



# cartopy dependencices
# - sudo pip install pyshp
# - sudo pip install six

# do actual installation
# - sudo /usr/bin/python setup.py build_ext --inplace install
#####- sudo /usr/bin/python setup.py build_ext  does not work yet!
# - sudo sh compile_extensions.sh

script:
 - nosetests 






